In [1]:
#import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#import and read teh charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN'
application_df = application_df.drop(columns = ['EIN'])
application_df

,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...,...
34294,THE LIONS CLUB OF HONOLULU KAMEHAMEHA,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,INTERNATIONAL ASSOCIATION OF LIONS CLUBS,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,PTA HAWAII CONGRESS,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,AMERICAN FEDERATION OF GOVERNMENT EMPLOYEES LO...,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,WATERHOUSE CHARITABLE TR,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [3]:
# Determine the number of unique values in each column.
application_df.nunique()

NAME                      19568
APPLICATION_TYPE             17
AFFILIATION                   6
CLASSIFICATION               71
USE_CASE                      5
ORGANIZATION                  4
STATUS                        2
INCOME_AMT                    9
SPECIAL_CONSIDERATIONS        2
ASK_AMT                    8747
IS_SUCCESSFUL                 2
dtype: int64

In [4]:
# Drop the non-beneficial ID columns, 'ASK_AMT	'.
application_df = application_df.drop(columns = ['ASK_AMT'])
application_df

,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,IS_SUCCESSFUL
0,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,1
1,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,1
2,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,0
3,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,1
4,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,1
...,...,...,...,...,...,...,...,...,...,...
34294,THE LIONS CLUB OF HONOLULU KAMEHAMEHA,T4,Independent,C1000,ProductDev,Association,1,0,N,0
34295,INTERNATIONAL ASSOCIATION OF LIONS CLUBS,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,0
34296,PTA HAWAII CONGRESS,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,0
34297,AMERICAN FEDERATION OF GOVERNMENT EMPLOYEES LO...,T5,Independent,C3000,ProductDev,Association,1,0,N,1
34298,WATERHOUSE CHARITABLE TR,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,0

In [5]:
# Determine the number of unique values in each column.
application_df.nunique()

NAME                      19568
APPLICATION_TYPE             17
AFFILIATION                   6
CLASSIFICATION               71
USE_CASE                      5
ORGANIZATION                  4
STATUS                        2
INCOME_AMT                    9
SPECIAL_CONSIDERATIONS        2
IS_SUCCESSFUL                 2
dtype: int64

In [6]:
#Look at APPLICATION_TYPE value counts to identify and replace with "Other"
counts = application_df['APPLICATION_TYPE'].value_counts()
counts

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [7]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(counts[counts<500].index)
application_types_to_replace

['T9', 'T13', 'T12', 'T2', 'T25', 'T14', 'T29', 'T15', 'T17']

In [8]:
# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other_app_type")

In [9]:
# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3                27037
T4                 1542
T6                 1216
T5                 1173
T19                1065
T8                  737
T7                  725
T10                 528
Other_app_type      276
Name: count, dtype: int64

In [10]:
#look at CLASSIFICATION value counts to identify and replace with "other"
classification_types = application_df['CLASSIFICATION'].value_counts()
classification_types

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [11]:
#look at CLASSIFICATION value counts >1
countsclassification = classification_types[classification_types>1]
countsclassification

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [12]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(classification_types[classification_types<100].index)
classifications_to_replace

['C2800',
 'C7100',
 'C1300',
 'C1280',
 'C1230',
 'C1400',
 'C7200',
 'C2300',
 'C1240',
 'C8000',
 'C7120',
 'C1500',
 'C1800',
 'C6000',
 'C1250',
 'C8200',
 'C1238',
 'C1278',
 'C1235',
 'C1237',
 'C7210',
 'C2400',
 'C1720',
 'C4100',
 'C1257',
 'C1600',
 'C1260',
 'C2710',
 'C0',
 'C3200',
 'C1234',
 'C1246',
 'C1267',
 'C1256',
 'C2190',
 'C4200',
 'C2600',
 'C5200',
 'C1370',
 'C1248',
 'C6100',
 'C1820',
 'C1900',
 'C1236',
 'C3700',
 'C2570',
 'C1580',
 'C1245',
 'C2500',
 'C1570',
 'C1283',
 'C2380',
 'C1732',
 'C1728',
 'C2170',
 'C4120',
 'C8210',
 'C2561',
 'C4500',
 'C2150']

In [13]:
# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other_classification")

In [14]:
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000                   17326
C2000                    6074
C1200                    4837
C3000                    1918
C2100                    1883
C7000                     777
Other_classification      669
C1700                     287
C4000                     194
C5000                     116
C1270                     114
C2700                     104
Name: count, dtype: int64

In [15]:
#convert the categorical data in numeric using get_dummies()
application_df = pd.get_dummies(application_df,dtype=float)
application_df.head()

,STATUS,IS_SUCCESSFUL,NAME_1 DAY RANCH RESCUE AND RURAL OKLAHOMA ANIMAL RESOURCE INC,NAME_100 BLACK MEN OF AMERICA,NAME_100 BLACK MEN OF MEMPHIS INC,NAME_100 BLACK MEN OF WEST GEORGIA INC,NAME_1150 WEBSTER STREET INC,NAME_116TH CAVALRY REGIMENT CHAPTER OF THE US CAVALRY & ARMOR ASSOCIATION,NAME_13TH BOMB SQUADRON ASSOCIATION,NAME_146TH ALUMNI ASSOCIATION,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [16]:
# Split our preprocessed data into our features and target arrays
y = application_df['IS_SUCCESSFUL'].values
y

array([1, 1, 0, ..., 0, 1, 0])

In [17]:
# drop 'IS SUCCESSFUL'
X = application_df.drop('IS_SUCCESSFUL', axis=1).values
X

array([[1., 0., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 1., 0.],
       ...,
       [1., 0., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 1., 0.]])

In [18]:
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state = 42)

In [19]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [20]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len( X_train_scaled[0])
hidden_nodes_layer1=7
hidden_nodes_layer2=14
hidden_nodes_layer3=21
nn = tf.keras.models.Sequential()

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation='relu'))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation='relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 7)                 137319

 dense_1 (Dense)             (None, 14)                112

 dense_2 (Dense)             (None, 1)                 15

=================================================================
Total params: 137446 (536.90 KB)
Trainable params: 137446 (536.90 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [21]:
# Compile the model
nn.compile(loss = 'binary_crossentropy', optimizer = 'adam', metrics=['accuracy'])

In [22]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,validation_split=0.15, epochs=100)

Epoch 1/100
684/684 [==============================] - 4s 5ms/step - loss: 0.5068 - accuracy: 0.7470 - val_loss: 0.4637 - val_accuracy: 0.7777
Epoch 2/100
684/684 [==============================] - 3s 4ms/step - loss: 0.2871 - accuracy: 0.8654 - val_loss: 0.5138 - val_accuracy: 0.7668
Epoch 3/100
684/684 [==============================] - 3s 4ms/step - loss: 0.2114 - accuracy: 0.9059 - val_loss: 0.6304 - val_accuracy: 0.6053
Epoch 4/100
684/684 [==============================] - 3s 4ms/step - loss: 0.1647 - accuracy: 0.9298 - val_loss: 0.5198 - val_accuracy: 0.7209
Epoch 5/100
684/684 [==============================] - 3s 4ms/step - loss: 0.1326 - accuracy: 0.9402 - val_loss: 0.5162 - val_accuracy: 0.7704
Epoch 6/100
684/684 [==============================] - 3s 4ms/step - loss: 0.1186 - accuracy: 0.9474 - val_loss: 0.5388 - val_accuracy: 0.7411
Epoch 7/100
684/684 [==============================] - 3s 4ms/step - loss: 0.1109 - accuracy: 0.9518 - val_loss: 0.5708 - val_accuracy: 0.7010
Epoch 8/100
684/684 [==============================] - 3s 4ms/step - loss: 0.1059 - accuracy: 0.9566 - val_loss: 0.5794 - val_accuracy: 0.6743
Epoch 9/100
684/684 [==============================] - 3s 4ms/step - loss: 0.1012 - accuracy: 0.9588 - val_loss: 0.5331 - val_accuracy: 0.7422
Epoch 10/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0983 - accuracy: 0.9607 - val_loss: 0.5247 - val_accuracy: 0.7287
Epoch 11/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0963 - accuracy: 0.9606 - val_loss: 0.5779 - val_accuracy: 0.7287
Epoch 12/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0947 - accuracy: 0.9618 - val_loss: 0.5273 - val_accuracy: 0.7362
Epoch 13/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0936 - accuracy: 0.9615 - val_loss: 0.5647 - val_accuracy: 0.7113
Epoch 14/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0922 - accuracy: 0.9616 - val_loss: 0.5672 - val_accuracy: 0.7497
Epoch 15/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0920 - accuracy: 0.9623 - val_loss: 0.5907 - val_accuracy: 0.7129
Epoch 16/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0906 - accuracy: 0.9633 - val_loss: 0.6703 - val_accuracy: 0.6745
Epoch 17/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0896 - accuracy: 0.9634 - val_loss: 0.6556 - val_accuracy: 0.6789
Epoch 18/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0900 - accuracy: 0.9636 - val_loss: 0.6551 - val_accuracy: 0.6870
Epoch 19/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0888 - accuracy: 0.9644 - val_loss: 0.6123 - val_accuracy: 0.7253
Epoch 20/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0888 - accuracy: 0.9635 - val_loss: 0.6149 - val_accuracy: 0.7248
Epoch 21/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0884 - accuracy: 0.9640 - val_loss: 0.6051 - val_accuracy: 0.7253
Epoch 22/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0882 - accuracy: 0.9640 - val_loss: 0.6693 - val_accuracy: 0.6994
Epoch 23/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0880 - accuracy: 0.9632 - val_loss: 0.6408 - val_accuracy: 0.7147
Epoch 24/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0869 - accuracy: 0.9646 - val_loss: 0.6232 - val_accuracy: 0.7336
Epoch 25/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0870 - accuracy: 0.9646 - val_loss: 0.6119 - val_accuracy: 0.7067
Epoch 26/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0870 - accuracy: 0.9635 - val_loss: 0.5416 - val_accuracy: 0.7927
Epoch 27/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0880 - accuracy: 0.9617 - val_loss: 0.5257 - val_accuracy: 0.7854
Epoch 28/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0864 - accuracy: 0.9638 - val_loss: 0.5070 - val_accuracy: 0.7650
Epoch 29/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0859 - accuracy: 0.9643 - val_loss: 0.6712 - val_accuracy: 0.7999
Epoch 30/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0911 - accuracy: 0.9604 - val_loss: 0.9475 - val_accuracy: 0.8012
Epoch 31/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0865 - accuracy: 0.9631 - val_loss: 0.8503 - val_accuracy: 0.8018
Epoch 32/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0839 - accuracy: 0.9644 - val_loss: 0.8671 - val_accuracy: 0.8015
Epoch 33/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0837 - accuracy: 0.9645 - val_loss: 0.8329 - val_accuracy: 0.8010
Epoch 34/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0832 - accuracy: 0.9651 - val_loss: 0.8781 - val_accuracy: 0.8018
Epoch 35/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0829 - accuracy: 0.9651 - val_loss: 0.9154 - val_accuracy: 0.8031
Epoch 36/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0825 - accuracy: 0.9651 - val_loss: 0.9344 - val_accuracy: 0.8020
Epoch 37/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0827 - accuracy: 0.9651 - val_loss: 0.9244 - val_accuracy: 0.8010
Epoch 38/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0824 - accuracy: 0.9653 - val_loss: 0.9721 - val_accuracy: 0.8038
Epoch 39/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0828 - accuracy: 0.9651 - val_loss: 0.9202 - val_accuracy: 0.8028
Epoch 40/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0826 - accuracy: 0.9647 - val_loss: 1.5917 - val_accuracy: 0.8015
Epoch 41/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0822 - accuracy: 0.9654 - val_loss: 1.6976 - val_accuracy: 0.7989
Epoch 42/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0825 - accuracy: 0.9649 - val_loss: 1.7787 - val_accuracy: 0.8010
Epoch 43/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0823 - accuracy: 0.9650 - val_loss: 1.8580 - val_accuracy: 0.8020
Epoch 44/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0820 - accuracy: 0.9656 - val_loss: 1.9303 - val_accuracy: 0.8025
Epoch 45/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0820 - accuracy: 0.9649 - val_loss: 1.8481 - val_accuracy: 0.8020
Epoch 46/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0818 - accuracy: 0.9655 - val_loss: 1.7544 - val_accuracy: 0.8036
Epoch 47/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0820 - accuracy: 0.9651 - val_loss: 1.7377 - val_accuracy: 0.8015
Epoch 48/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0816 - accuracy: 0.9658 - val_loss: 1.7646 - val_accuracy: 0.8018
Epoch 49/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0819 - accuracy: 0.9654 - val_loss: 1.8928 - val_accuracy: 0.8018
Epoch 50/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0816 - accuracy: 0.9659 - val_loss: 1.8187 - val_accuracy: 0.8012
Epoch 51/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0818 - accuracy: 0.9657 - val_loss: 1.8711 - val_accuracy: 0.8020
Epoch 52/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0818 - accuracy: 0.9657 - val_loss: 1.9439 - val_accuracy: 0.8012
Epoch 53/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0816 - accuracy: 0.9657 - val_loss: 1.9544 - val_accuracy: 0.8025
Epoch 54/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0814 - accuracy: 0.9657 - val_loss: 1.9819 - val_accuracy: 0.8023
Epoch 55/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0816 - accuracy: 0.9656 - val_loss: 1.7748 - val_accuracy: 0.8007
Epoch 56/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0814 - accuracy: 0.9656 - val_loss: 1.6511 - val_accuracy: 0.8005
Epoch 57/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0813 - accuracy: 0.9659 - val_loss: 1.8002 - val_accuracy: 0.8010
Epoch 58/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0815 - accuracy: 0.9657 - val_loss: 1.7324 - val_accuracy: 0.7997
Epoch 59/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0817 - accuracy: 0.9651 - val_loss: 1.6121 - val_accuracy: 0.8010
Epoch 60/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0815 - accuracy: 0.9658 - val_loss: 1.7849 - val_accuracy: 0.8012
Epoch 61/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0811 - accuracy: 0.9652 - val_loss: 1.7586 - val_accuracy: 0.8018
Epoch 62/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0814 - accuracy: 0.9657 - val_loss: 1.9056 - val_accuracy: 0.7989
Epoch 63/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0815 - accuracy: 0.9651 - val_loss: 1.7652 - val_accuracy: 0.8015
Epoch 64/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0812 - accuracy: 0.9653 - val_loss: 1.8645 - val_accuracy: 0.8018
Epoch 65/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0810 - accuracy: 0.9657 - val_loss: 2.1066 - val_accuracy: 0.8005
Epoch 66/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0815 - accuracy: 0.9660 - val_loss: 1.6948 - val_accuracy: 0.8007
Epoch 67/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0813 - accuracy: 0.9653 - val_loss: 1.6909 - val_accuracy: 0.8018
Epoch 68/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0810 - accuracy: 0.9656 - val_loss: 1.6314 - val_accuracy: 0.8020
Epoch 69/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0809 - accuracy: 0.9655 - val_loss: 1.6993 - val_accuracy: 0.8015
Epoch 70/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0803 - accuracy: 0.9661 - val_loss: 1.6409 - val_accuracy: 0.8015
Epoch 71/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0809 - accuracy: 0.9664 - val_loss: 1.6341 - val_accuracy: 0.8012
Epoch 72/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0809 - accuracy: 0.9655 - val_loss: 1.7914 - val_accuracy: 0.8007
Epoch 73/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0815 - accuracy: 0.9656 - val_loss: 1.7031 - val_accuracy: 0.8012
Epoch 74/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0808 - accuracy: 0.9658 - val_loss: 1.5883 - val_accuracy: 0.8018
Epoch 75/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0806 - accuracy: 0.9660 - val_loss: 1.6681 - val_accuracy: 0.8007
Epoch 76/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0805 - accuracy: 0.9661 - val_loss: 1.6823 - val_accuracy: 0.8015
Epoch 77/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0806 - accuracy: 0.9659 - val_loss: 1.6721 - val_accuracy: 0.8015
Epoch 78/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0803 - accuracy: 0.9661 - val_loss: 1.7770 - val_accuracy: 0.8018
Epoch 79/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0807 - accuracy: 0.9659 - val_loss: 1.6309 - val_accuracy: 0.8005
Epoch 80/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0801 - accuracy: 0.9662 - val_loss: 1.6687 - val_accuracy: 0.8007
Epoch 81/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0805 - accuracy: 0.9662 - val_loss: 1.7514 - val_accuracy: 0.8018
Epoch 82/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0805 - accuracy: 0.9664 - val_loss: 1.5931 - val_accuracy: 0.8023
Epoch 83/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0803 - accuracy: 0.9663 - val_loss: 1.5706 - val_accuracy: 0.8025
Epoch 84/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0802 - accuracy: 0.9663 - val_loss: 1.4741 - val_accuracy: 0.8036
Epoch 85/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0801 - accuracy: 0.9662 - val_loss: 1.5454 - val_accuracy: 0.8033
Epoch 86/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0799 - accuracy: 0.9662 - val_loss: 1.8309 - val_accuracy: 0.8012
Epoch 87/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0799 - accuracy: 0.9659 - val_loss: 1.6927 - val_accuracy: 0.8020
Epoch 88/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0802 - accuracy: 0.9659 - val_loss: 1.8139 - val_accuracy: 0.8015
Epoch 89/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0804 - accuracy: 0.9664 - val_loss: 1.4616 - val_accuracy: 0.8010
Epoch 90/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0799 - accuracy: 0.9657 - val_loss: 1.5220 - val_accuracy: 0.8018
Epoch 91/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0800 - accuracy: 0.9666 - val_loss: 1.5035 - val_accuracy: 0.8007
Epoch 92/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0799 - accuracy: 0.9664 - val_loss: 1.8141 - val_accuracy: 0.8038
Epoch 93/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0801 - accuracy: 0.9661 - val_loss: 1.8168 - val_accuracy: 0.8018
Epoch 94/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0801 - accuracy: 0.9662 - val_loss: 1.8953 - val_accuracy: 0.8025
Epoch 95/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0799 - accuracy: 0.9664 - val_loss: 1.8148 - val_accuracy: 0.8028
Epoch 96/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0799 - accuracy: 0.9659 - val_loss: 1.5088 - val_accuracy: 0.8020
Epoch 97/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0798 - accuracy: 0.9666 - val_loss: 1.5021 - val_accuracy: 0.7994
Epoch 98/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0798 - accuracy: 0.9663 - val_loss: 1.5991 - val_accuracy: 0.8002
Epoch 99/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0799 - accuracy: 0.9659 - val_loss: 1.7988 - val_accuracy: 0.8002
Epoch 100/100
684/684 [==============================] - 3s 4ms/step - loss: 0.0798 - accuracy: 0.9660 - val_loss: 1.8549 - val_accuracy: 0.8031

In [23]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.6283 - accuracy: 0.7683 - 446ms/epoch - 2ms/step
Loss: 0.6282585263252258, Accuracy: 0.7682799100875854

In [24]:
# Export our model to HDF5 file
from google.colab import files
filepath = r"C:/Users/rociocuao/Downloads/AlphabetSoupCharity_Optimization_Final.h5"
nn.save(filepath, save_format='h5')
files.download(filepath)

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(